<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LOVELESH" failures="1" tests="3" name="Personal Loan" time="0.108" errors="0" timestamp="07 Mar 2024 06:54:31 GMT">
  <testcase classname="test.Day1" name="test1" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.Day1.test1(Day1.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="test.Day2" name="test1" time="0.011"/>
  <testcase classname="test.Day4" name="MobileLoginHomeLoan" time="0.01"/>
  <testcase classname="test.Day1" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="test.Day4" name="LoginAPIHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- LoginAPIHomeLoan -->
  <testcase classname="test.Day4" name="WebLoginHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- WebLoginHomeLoan -->
</testsuite> <!-- Personal Loan -->
